import asyncio
import uuid


async def _register_and_login(client, email: str) -> str:
    await client.post(
        "/api/auth/register",
        json={"email": email, "password": "supersecret1", "full_name": "Test User"},
    )
    resp = await client.post("/api/auth/login", json={"email": email, "password": "supersecret1"})
    return resp.json()["access_token"]


async def test_assistant_replies_to_chat_message(client, unique_email):
    token = await _register_and_login(client, unique_email)
    headers = {"Authorization": f"Bearer {token}"}

    body = f"do you have appointment slots? {uuid.uuid4().hex[:6]}"
    resp = await client.post(
        "/api/messages", json={"channel": "chat", "body": body}, headers=headers
    )
    assert resp.status_code == 201
    my_message_id = resp.json()["id"]

    # Reply is generated by a fire-and-forget task; poll briefly.
    reply = None
    for _ in range(20):
        await asyncio.sleep(0.25)
        resp = await client.get("/api/messages", headers=headers)
        messages = resp.json()
        ours = next(i for i, m in enumerate(messages) if m["id"] == my_message_id)
        later = messages[ours + 1 :]
        if later:
            reply = later[-1]
            break

    assert reply is not None, "assistant reply never arrived"
    assert reply["sender_id"] == "00000000-0000-4000-8000-00000000a1a1"
    assert len(reply["body"]) > 0
    # No API key in tests — fallback responder should mention appointments.
    assert "appointment" in reply["body"].lower()
